development:
  sessions:
    default:
      database: market_dota2_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: market_dota2_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      uri: 'mongodb://heroku_znkmpkg0:sn0ucvkq5bsc13i6ld0e77fh1@ds035663.mongolab.com:35663/heroku_znkmpkg0'
  options:
    raise_not_found_error: false
    max_retries: 30
    retry_interval: 1
    timeout: 15
    refresh_interval: 10

